/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_pure = 1,
  anon_sym_strict = 2,
  anon_sym_provable = 3,
  anon_sym_free = 4,
  anon_sym_sort = 5,
  anon_sym_term = 6,
  anon_sym_COLON = 7,
  anon_sym_SEMI = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_GT = 13,
  anon_sym__ = 14,
  anon_sym_axiom = 15,
  anon_sym_theorem = 16,
  sym__math_string = 17,
  sym_identifier = 18,
  sym_source_file = 19,
  sym__statement = 20,
  sym__sort_stmt = 21,
  sym__term_stmt = 22,
  sym__type_binder = 23,
  sym__arrow_type = 24,
  sym_type = 25,
  sym__identifier_ = 26,
  sym__assert_stmt = 27,
  sym__formula_type_binder = 28,
  sym__formula_arrow_type = 29,
  sym__formula = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym__term_stmt_repeat1 = 32,
  aux_sym__type_binder_repeat1 = 33,
  aux_sym__type_binder_repeat2 = 34,
  aux_sym__assert_stmt_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_pure] = "pure",
  [anon_sym_strict] = "strict",
  [anon_sym_provable] = "provable",
  [anon_sym_free] = "free",
  [anon_sym_sort] = "sort",
  [anon_sym_term] = "term",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_GT] = ">",
  [anon_sym__] = "_",
  [anon_sym_axiom] = "axiom",
  [anon_sym_theorem] = "theorem",
  [sym__math_string] = "_math_string",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__sort_stmt] = "_sort_stmt",
  [sym__term_stmt] = "_term_stmt",
  [sym__type_binder] = "_type_binder",
  [sym__arrow_type] = "_arrow_type",
  [sym_type] = "type",
  [sym__identifier_] = "_identifier_",
  [sym__assert_stmt] = "_assert_stmt",
  [sym__formula_type_binder] = "_formula_type_binder",
  [sym__formula_arrow_type] = "_formula_arrow_type",
  [sym__formula] = "_formula",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__term_stmt_repeat1] = "_term_stmt_repeat1",
  [aux_sym__type_binder_repeat1] = "_type_binder_repeat1",
  [aux_sym__type_binder_repeat2] = "_type_binder_repeat2",
  [aux_sym__assert_stmt_repeat1] = "_assert_stmt_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_pure] = anon_sym_pure,
  [anon_sym_strict] = anon_sym_strict,
  [anon_sym_provable] = anon_sym_provable,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_sort] = anon_sym_sort,
  [anon_sym_term] = anon_sym_term,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym__] = anon_sym__,
  [anon_sym_axiom] = anon_sym_axiom,
  [anon_sym_theorem] = anon_sym_theorem,
  [sym__math_string] = sym__math_string,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__sort_stmt] = sym__sort_stmt,
  [sym__term_stmt] = sym__term_stmt,
  [sym__type_binder] = sym__type_binder,
  [sym__arrow_type] = sym__arrow_type,
  [sym_type] = sym_type,
  [sym__identifier_] = sym__identifier_,
  [sym__assert_stmt] = sym__assert_stmt,
  [sym__formula_type_binder] = sym__formula_type_binder,
  [sym__formula_arrow_type] = sym__formula_arrow_type,
  [sym__formula] = sym__formula,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__term_stmt_repeat1] = aux_sym__term_stmt_repeat1,
  [aux_sym__type_binder_repeat1] = aux_sym__type_binder_repeat1,
  [aux_sym__type_binder_repeat2] = aux_sym__type_binder_repeat2,
  [aux_sym__assert_stmt_repeat1] = aux_sym__assert_stmt_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_pure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_strict] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_provable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sort] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_term] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_axiom] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theorem] = {
    .visible = true,
    .named = false,
  },
  [sym__math_string] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__sort_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym__term_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym__type_binder] = {
    .visible = false,
    .named = true,
  },
  [sym__arrow_type] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_] = {
    .visible = false,
    .named = true,
  },
  [sym__assert_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym__formula_type_binder] = {
    .visible = false,
    .named = true,
  },
  [sym__formula_arrow_type] = {
    .visible = false,
    .named = true,
  },
  [sym__formula] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__term_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__type_binder_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__type_binder_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__assert_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '$', 2,
        '(', 45,
        ')', 46,
        ':', 41,
        ';', 42,
        '>', 47,
        '_', 48,
        'a', 33,
        'f', 23,
        'p', 24,
        's', 20,
        't', 12,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '>') ADVANCE(47);
      if (lookahead == '_') ADVANCE(48);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(51);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'v') ADVANCE(3);
      END_STATE();
    case 33:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_pure);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_strict);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_provable);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_sort);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_term);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_axiom);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_theorem);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__math_string);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_pure] = ACTIONS(1),
    [anon_sym_strict] = ACTIONS(1),
    [anon_sym_provable] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_sort] = ACTIONS(1),
    [anon_sym_term] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_axiom] = ACTIONS(1),
    [anon_sym_theorem] = ACTIONS(1),
    [sym__math_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(61),
    [sym__statement] = STATE(3),
    [sym__sort_stmt] = STATE(3),
    [sym__term_stmt] = STATE(3),
    [sym__assert_stmt] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_pure] = ACTIONS(5),
    [anon_sym_strict] = ACTIONS(7),
    [anon_sym_provable] = ACTIONS(9),
    [anon_sym_free] = ACTIONS(11),
    [anon_sym_sort] = ACTIONS(13),
    [anon_sym_term] = ACTIONS(15),
    [anon_sym_axiom] = ACTIONS(17),
    [anon_sym_theorem] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_pure,
    ACTIONS(24), 1,
      anon_sym_strict,
    ACTIONS(27), 1,
      anon_sym_provable,
    ACTIONS(30), 1,
      anon_sym_free,
    ACTIONS(33), 1,
      anon_sym_sort,
    ACTIONS(36), 1,
      anon_sym_term,
    ACTIONS(39), 2,
      anon_sym_axiom,
      anon_sym_theorem,
    STATE(2), 5,
      sym__statement,
      sym__sort_stmt,
      sym__term_stmt,
      sym__assert_stmt,
      aux_sym_source_file_repeat1,
  [33] = 9,
    ACTIONS(5), 1,
      anon_sym_pure,
    ACTIONS(7), 1,
      anon_sym_strict,
    ACTIONS(9), 1,
      anon_sym_provable,
    ACTIONS(11), 1,
      anon_sym_free,
    ACTIONS(13), 1,
      anon_sym_sort,
    ACTIONS(15), 1,
      anon_sym_term,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      anon_sym_axiom,
      anon_sym_theorem,
    STATE(2), 5,
      sym__statement,
      sym__sort_stmt,
      sym__term_stmt,
      sym__assert_stmt,
      aux_sym_source_file_repeat1,
  [66] = 1,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [78] = 1,
    ACTIONS(46), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [90] = 1,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [102] = 1,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [114] = 1,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [126] = 1,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [138] = 1,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [150] = 1,
    ACTIONS(58), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [162] = 1,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_pure,
      anon_sym_strict,
      anon_sym_provable,
      anon_sym_free,
      anon_sym_sort,
      anon_sym_term,
      anon_sym_axiom,
      anon_sym_theorem,
  [174] = 3,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(13), 1,
      aux_sym__type_binder_repeat1,
    ACTIONS(62), 5,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [188] = 3,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(15), 1,
      aux_sym__type_binder_repeat1,
    ACTIONS(67), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [201] = 3,
    ACTIONS(73), 1,
      sym_identifier,
    STATE(13), 1,
      aux_sym__type_binder_repeat1,
    ACTIONS(71), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [214] = 3,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym__,
      sym_identifier,
    STATE(28), 2,
      sym__identifier_,
      aux_sym__type_binder_repeat2,
  [226] = 3,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(81), 2,
      anon_sym__,
      sym_identifier,
    STATE(16), 2,
      sym__identifier_,
      aux_sym__type_binder_repeat2,
  [238] = 4,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    STATE(19), 2,
      sym__formula_type_binder,
      aux_sym__assert_stmt_repeat1,
  [252] = 4,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_COLON,
    STATE(24), 2,
      sym__formula_type_binder,
      aux_sym__assert_stmt_repeat1,
  [266] = 4,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    STATE(25), 2,
      sym__type_binder,
      aux_sym__term_stmt_repeat1,
  [280] = 4,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      anon_sym_LPAREN,
    STATE(21), 2,
      sym__type_binder,
      aux_sym__term_stmt_repeat1,
  [294] = 3,
    ACTIONS(105), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym__,
      sym_identifier,
    STATE(28), 2,
      sym__identifier_,
      aux_sym__type_binder_repeat2,
  [306] = 5,
    ACTIONS(107), 1,
      sym__math_string,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(56), 1,
      sym__formula,
    STATE(70), 1,
      sym__formula_arrow_type,
    STATE(78), 1,
      sym_type,
  [322] = 4,
    ACTIONS(111), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    STATE(24), 2,
      sym__formula_type_binder,
      aux_sym__assert_stmt_repeat1,
  [336] = 4,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_COLON,
    STATE(21), 2,
      sym__type_binder,
      aux_sym__term_stmt_repeat1,
  [350] = 3,
    ACTIONS(121), 1,
      anon_sym_COLON,
    ACTIONS(123), 2,
      anon_sym__,
      sym_identifier,
    STATE(22), 2,
      sym__identifier_,
      aux_sym__type_binder_repeat2,
  [362] = 5,
    ACTIONS(107), 1,
      sym__math_string,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(56), 1,
      sym__formula,
    STATE(77), 1,
      sym__formula_arrow_type,
    STATE(78), 1,
      sym_type,
  [378] = 3,
    ACTIONS(125), 1,
      anon_sym_COLON,
    ACTIONS(127), 2,
      anon_sym__,
      sym_identifier,
    STATE(28), 2,
      sym__identifier_,
      aux_sym__type_binder_repeat2,
  [390] = 5,
    ACTIONS(107), 1,
      sym__math_string,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(56), 1,
      sym__formula,
    STATE(78), 1,
      sym_type,
    STATE(81), 1,
      sym__formula_arrow_type,
  [406] = 3,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(130), 1,
      sym__math_string,
    STATE(68), 2,
      sym_type,
      sym__formula,
  [417] = 4,
    ACTIONS(132), 1,
      anon_sym_strict,
    ACTIONS(134), 1,
      anon_sym_provable,
    ACTIONS(136), 1,
      anon_sym_free,
    ACTIONS(138), 1,
      anon_sym_sort,
  [430] = 3,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(140), 1,
      sym__math_string,
    STATE(80), 2,
      sym_type,
      sym__formula,
  [441] = 3,
    ACTIONS(142), 1,
      anon_sym_COLON,
    ACTIONS(144), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym__type_binder_repeat1,
  [451] = 3,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym__type_binder_repeat1,
  [461] = 3,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type,
    STATE(57), 1,
      sym__arrow_type,
  [471] = 3,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym__type_binder_repeat1,
  [481] = 3,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type,
    STATE(72), 1,
      sym__arrow_type,
  [491] = 3,
    ACTIONS(150), 1,
      anon_sym_provable,
    ACTIONS(152), 1,
      anon_sym_free,
    ACTIONS(154), 1,
      anon_sym_sort,
  [501] = 3,
    ACTIONS(156), 1,
      anon_sym_COLON,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(34), 1,
      aux_sym__type_binder_repeat1,
  [511] = 3,
    ACTIONS(134), 1,
      anon_sym_provable,
    ACTIONS(136), 1,
      anon_sym_free,
    ACTIONS(138), 1,
      anon_sym_sort,
  [521] = 1,
    ACTIONS(160), 3,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [527] = 3,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type,
    STATE(59), 1,
      sym__arrow_type,
  [537] = 1,
    ACTIONS(162), 3,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [543] = 1,
    ACTIONS(164), 3,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [549] = 1,
    ACTIONS(166), 3,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [555] = 2,
    ACTIONS(136), 1,
      anon_sym_free,
    ACTIONS(138), 1,
      anon_sym_sort,
  [562] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(66), 1,
      sym_type,
  [569] = 2,
    ACTIONS(168), 1,
      anon_sym_free,
    ACTIONS(170), 1,
      anon_sym_sort,
  [576] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(74), 1,
      sym_type,
  [583] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(75), 1,
      sym_type,
  [590] = 2,
    ACTIONS(172), 1,
      anon_sym_SEMI,
    ACTIONS(174), 1,
      anon_sym_GT,
  [597] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(82), 1,
      sym_type,
  [604] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(79), 1,
      sym_type,
  [611] = 2,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(60), 1,
      sym_type,
  [618] = 2,
    ACTIONS(152), 1,
      anon_sym_free,
    ACTIONS(154), 1,
      anon_sym_sort,
  [625] = 2,
    ACTIONS(176), 1,
      anon_sym_SEMI,
    ACTIONS(178), 1,
      anon_sym_GT,
  [632] = 1,
    ACTIONS(180), 1,
      anon_sym_SEMI,
  [636] = 1,
    ACTIONS(182), 1,
      sym_identifier,
  [640] = 1,
    ACTIONS(184), 1,
      anon_sym_SEMI,
  [644] = 1,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
  [648] = 1,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
  [652] = 1,
    ACTIONS(190), 1,
      sym_identifier,
  [656] = 1,
    ACTIONS(192), 1,
      sym_identifier,
  [660] = 1,
    ACTIONS(194), 1,
      anon_sym_sort,
  [664] = 1,
    ACTIONS(196), 1,
      sym_identifier,
  [668] = 1,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
  [672] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [676] = 1,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
  [680] = 1,
    ACTIONS(170), 1,
      anon_sym_sort,
  [684] = 1,
    ACTIONS(202), 1,
      anon_sym_SEMI,
  [688] = 1,
    ACTIONS(204), 1,
      sym_identifier,
  [692] = 1,
    ACTIONS(206), 1,
      anon_sym_SEMI,
  [696] = 1,
    ACTIONS(154), 1,
      anon_sym_sort,
  [700] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
  [704] = 1,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
  [708] = 1,
    ACTIONS(210), 1,
      sym_identifier,
  [712] = 1,
    ACTIONS(212), 1,
      anon_sym_SEMI,
  [716] = 1,
    ACTIONS(178), 1,
      anon_sym_GT,
  [720] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
  [724] = 1,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
  [728] = 1,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [732] = 1,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
  [736] = 1,
    ACTIONS(138), 1,
      anon_sym_sort,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 90,
  [SMALL_STATE(7)] = 102,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 126,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 150,
  [SMALL_STATE(12)] = 162,
  [SMALL_STATE(13)] = 174,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 201,
  [SMALL_STATE(16)] = 214,
  [SMALL_STATE(17)] = 226,
  [SMALL_STATE(18)] = 238,
  [SMALL_STATE(19)] = 252,
  [SMALL_STATE(20)] = 266,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 294,
  [SMALL_STATE(23)] = 306,
  [SMALL_STATE(24)] = 322,
  [SMALL_STATE(25)] = 336,
  [SMALL_STATE(26)] = 350,
  [SMALL_STATE(27)] = 362,
  [SMALL_STATE(28)] = 378,
  [SMALL_STATE(29)] = 390,
  [SMALL_STATE(30)] = 406,
  [SMALL_STATE(31)] = 417,
  [SMALL_STATE(32)] = 430,
  [SMALL_STATE(33)] = 441,
  [SMALL_STATE(34)] = 451,
  [SMALL_STATE(35)] = 461,
  [SMALL_STATE(36)] = 471,
  [SMALL_STATE(37)] = 481,
  [SMALL_STATE(38)] = 491,
  [SMALL_STATE(39)] = 501,
  [SMALL_STATE(40)] = 511,
  [SMALL_STATE(41)] = 521,
  [SMALL_STATE(42)] = 527,
  [SMALL_STATE(43)] = 537,
  [SMALL_STATE(44)] = 543,
  [SMALL_STATE(45)] = 549,
  [SMALL_STATE(46)] = 555,
  [SMALL_STATE(47)] = 562,
  [SMALL_STATE(48)] = 569,
  [SMALL_STATE(49)] = 576,
  [SMALL_STATE(50)] = 583,
  [SMALL_STATE(51)] = 590,
  [SMALL_STATE(52)] = 597,
  [SMALL_STATE(53)] = 604,
  [SMALL_STATE(54)] = 611,
  [SMALL_STATE(55)] = 618,
  [SMALL_STATE(56)] = 625,
  [SMALL_STATE(57)] = 632,
  [SMALL_STATE(58)] = 636,
  [SMALL_STATE(59)] = 640,
  [SMALL_STATE(60)] = 644,
  [SMALL_STATE(61)] = 648,
  [SMALL_STATE(62)] = 652,
  [SMALL_STATE(63)] = 656,
  [SMALL_STATE(64)] = 660,
  [SMALL_STATE(65)] = 664,
  [SMALL_STATE(66)] = 668,
  [SMALL_STATE(67)] = 672,
  [SMALL_STATE(68)] = 676,
  [SMALL_STATE(69)] = 680,
  [SMALL_STATE(70)] = 684,
  [SMALL_STATE(71)] = 688,
  [SMALL_STATE(72)] = 692,
  [SMALL_STATE(73)] = 696,
  [SMALL_STATE(74)] = 700,
  [SMALL_STATE(75)] = 704,
  [SMALL_STATE(76)] = 708,
  [SMALL_STATE(77)] = 712,
  [SMALL_STATE(78)] = 716,
  [SMALL_STATE(79)] = 720,
  [SMALL_STATE(80)] = 724,
  [SMALL_STATE(81)] = 728,
  [SMALL_STATE(82)] = 732,
  [SMALL_STATE(83)] = 736,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assert_stmt, 6, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sort_stmt, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sort_stmt, 4, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sort_stmt, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sort_stmt, 5, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_stmt, 5, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sort_stmt, 6, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assert_stmt, 5, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_stmt, 6, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__type_binder_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_binder_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__term_stmt_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__term_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__term_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__assert_stmt_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__assert_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__assert_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__type_binder_repeat2, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_binder_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_binder, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__formula_type_binder, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_binder, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__formula_type_binder, 5, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arrow_type, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__formula_arrow_type, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [188] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arrow_type, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__formula_arrow_type, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mm0(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mm0",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
